### ISSUE TITLE
GitHub Actions ci-cd workflow for GCP

### ISSUE THREAD

**Issue by nick-youngblut** [randy3k/shiny-cloudrun-demo#5]
In case you want to include a github actions ci-cd workflow that works with GCP, here's what works for me:

```yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: ci-cd

jobs:
  test:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: "ubuntu-20.04", r: "4.3.1"}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      APP: my-app-name
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
      - id: "Google-Auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      - uses: rstudio/shinytest2/actions/test-app@v1
        with:
          app-dir: "app"
          upload-snapshots: true
      - id: "gcloud-setup"
        name: "Set up GCP Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "${{ env.GCP_PROJECT_ID }}"
      - id: "Docker-Auth"
        name: "Docker authentication"
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
      - id: "Docker-Build" 
        name: "Build and push container"
        run: |
          docker build -t "us-west1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" .
          docker push "us-west1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
      - id: "Deploy"
        name: "Deploy to Cloud Run"
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: "${{ env.APP }}"
          image: "us-west1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
          region: "us-west1"
          flags: >
            --service-account=${{ env.GCP_SERVICE_ACCOUNT }}
            --port=8080
            --cpu=2
            --memory=3Gi
            --max-instances=1
            --concurrency=80
 ```
